name: Run performance tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    #- name: Run test
    #  run: poetry run python runner.py
    #  continue-on-error: true
    - name: A dummy test to test the commit process
      run:
        echo "Testing" > results/index.html
        echo "{}" > results/results.json
    - name: Switch branch without trashing results
      run: |
        git stash
        git fetch --depth=1
        git checkout gh-pages
        git stash apply
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_message: Run tests
        file_pattern: results/*
        skip_dirty_check: true

