name: Run performance tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run test
      run: poetry run python runner.py
      continue-on-error: true
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Run tests
        branch: gh-pages
        file_pattern: -f results/results.json results/index.html
        skip_dirty_check: true

