name: Run performance tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Run test
      run: poetry run python -u runner.py
      continue-on-error: true
    - name: Upload result as artifact
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: results/index.html
        retention-days: 7
    - name: Switch branch without trashing results
      run: |
        mv results results.stash
        git fetch --depth=1
        git checkout gh-pages
        mv results.stash/* results/
        git add --force results/*
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_message: Run tests
        file_pattern: results/*
        skip_dirty_check: true
